# Generated by Django 5.1.4 on 2025-04-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('hindi', 'Hindi'), ('english', 'English')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.CharField(choices=[('11', '11'), ('12', '12'), ('droper', 'Droper')], max_length=10)),
            ],
        ),
    ]
